---

- hosts: all
  tasks:
   - name: Download binary
     get_url:
      url: https://releases.hashicorp.com/vault/1.8.0/vault_1.8.0_linux_amd64.zip
      dest: /tmp/vault_1.8.0_linux_amd64.zip
     register: vault_download

   - name: "Unzip vault archive"
     unarchive:
      src: /tmp/vault_1.8.0_linux_amd64.zip
      dest: /usr/local/bin
      copy: no
      mode: 0755

   - name: "Set vault binary capabilities"
     capabilities:
      path: /usr/local/bin/vault
      capability: cap_ipc_lock+ep
      state: present

   - name: Copy systemd init file
     template:
      src: init.service.j2
      dest: /etc/systemd/system/vault.service
      owner: root
      group: root

   - name: config file
     template:
      src: vault.hcl.j2
      dest: /usr/local/bin/vault
      owner: root
      group: root

   - name: vault service
     service:
      name: vault
      state: started
      enabled: yes
